services:
  wb-service:
    container_name: web-service
    hostname: web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      db-service:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://admin:0000@db:5432/relais-finder?schema=public
    networks:
      - relais-finder-network

  db-service:
    image: postgres:latest
    restart: always
    container_name: database-service
    hostname: db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=0000
      - POSTGRES_DB=relais-finder
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
    volumes:
      - relais-finder-db-data:/var/lib/postgresql/data/
      - ./docker-entrypoint-initdb.d/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - relais-finder-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    hostname: adminer
    container_name: adminer-service
    ports:
      - 8080:8080
    depends_on:
      db-service:
        condition: service_healthy
    networks:
      - relais-finder-network

networks:
  relais-finder-network:
    driver: bridge

volumes:
  relais-finder-db-data:
